# Generated by Django 2.2.2 on 2019-07-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapid_responder', '0003_auto_20190708_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='conditions',
            field=models.ManyToManyField(related_name='qualifications', to='rapid_responder.Condition'),
        ),
    ]
