# Generated by Django 2.2.3 on 2019-07-11 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapid_responder', '0004_qualification_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='conditions',
            field=models.ManyToManyField(blank=True, related_name='qualifications', to='rapid_responder.Condition'),
        ),
    ]
