# Generated by Django 2.2.3 on 2019-07-16 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapid_responder', '0005_auto_20190711_1120'),
        ('rapid_responder', '0005_auto_20190710_2107'),
    ]

    operations = [
    ]
