# Generated by Django 2.2.2 on 2019-07-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapid_responder', '0006_merge_20190716_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='close_date',
            field=models.DateTimeField(null=True),
        ),
    ]
